// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {binance} from '../models';

export function Greet(arg1:string):Promise<string>;

export function KlineService(arg1:string,arg2:string,arg3:number):Promise<Array<binance.Kline>>;

export function KlineServiceWithStartAndEnd(arg1:string,arg2:number,arg3:number,arg4:string,arg5:number):Promise<Array<binance.Kline>>;
